# Generated by Django 5.0.6 on 2024-06-14 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_city_post_email_post_image_post_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='what are you looking for?')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='city or neighborhood')),
                ('description', models.TextField(default='', verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='pics')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('social_link', models.URLField(blank=True, null=True, verbose_name='Social Link')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
