# Generated by Django 5.0.6 on 2024-06-14 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_personalad_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalad',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='personalad',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='personalad',
            name='social_link',
            field=models.URLField(blank=True, null=True, verbose_name='social'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads', verbose_name='image')),
                ('personal_ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.personalad')),
            ],
        ),
    ]
