# Generated by Django 5.0.6 on 2024-06-14 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_personalad_email_alter_personalad_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='personal_ad',
        ),
        migrations.RemoveField(
            model_name='personalad',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='personalad',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.personalad'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
