# Generated by Django 5.0.6 on 2024-06-16 00:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_image_personal_ad_remove_personalad_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonalAd',
            new_name='Personal',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='personalad',
            new_name='personal',
        ),
    ]
