# Generated by Django 5.0.6 on 2024-06-16 01:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_personalad_personal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
