# Generated by Django 5.0.6 on 2024-06-17 02:16

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_personal_date_posted'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.FILER_IMAGE_MODEL)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.personal')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
