# Generated by Django 5.0.6 on 2024-06-19 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_personal_image_images_delete_personalimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='image1'),
        ),
        migrations.AddField(
            model_name='personal',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='image2'),
        ),
        migrations.AddField(
            model_name='personal',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='image3'),
        ),
        migrations.AddField(
            model_name='personal',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='image4'),
        ),
        migrations.AddField(
            model_name='personal',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='image5'),
        ),
        migrations.AddField(
            model_name='personal',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='image6'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='image1'),
        ),
    ]
