# Generated by Django 5.0.6 on 2024-07-03 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_personal_image1_personal_image2_personal_image3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='image1'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='image1'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='image2'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='image3'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='image4'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='image5'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='image6'),
        ),
    ]
